# Generated by Django 6.0.6 on 2026-06-20 08:25

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (7-15 digits, optional leading +).', regex='^\\+?\\d{7,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('company_name', models.CharField(blank=True, max_length=150)),
                ('id_proof_type', models.CharField(blank=True, choices=[('AADHAR', 'Aadhar Card'), ('PAN', 'PAN Card'), ('DL', 'Driving License'), ('PASSPORT', 'Passport'), ('OTHER', 'Other')], max_length=20)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visitor_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('MEETING', 'Meeting'), ('INTERVIEW', 'Interview'), ('DELIVERY', 'Delivery'), ('VENDOR', 'Vendor Visit'), ('PERSONAL', 'Personal'), ('OTHER', 'Other')], default='MEETING', max_length=20)),
                ('purpose_notes', models.CharField(blank=True, max_length=255)),
                ('check_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CHECKED_IN', 'Checked In'), ('CHECKED_OUT', 'Checked Out')], default='CHECKED_IN', max_length=12)),
                ('badge_number', models.CharField(blank=True, max_length=20)),
                ('host', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='visitors.host')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='visitors.visitor')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
